# Generated by Django 4.1.4 on 2022-12-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img_url',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(max_length=250),
        ),
    ]
